/* tslint:disable */
/* eslint-disable */
/**
 * EU Digital COVID Certificate Booking Demo
 * The API provides exemplary booking endpoints
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BookingRequest
 */
export interface BookingRequest {
    /**
     * 
     * @type {string}
     * @memberof BookingRequest
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingRequest
     */
    forename?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingRequest
     */
    lastname?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingRequest
     */
    birthDate?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingRequest
     */
    bookingReference?: any;
}
