/* tslint:disable */
/* eslint-disable */
/**
 * EU Digital COVID Certificate Booking Demo
 * The API provides exemplary booking endpoints
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BookingPassengerResponse
 */
export interface BookingPassengerResponse {
    /**
     * 
     * @type {string}
     * @memberof BookingPassengerResponse
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingPassengerResponse
     */
    forename?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingPassengerResponse
     */
    lastname?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingPassengerResponse
     */
    birthDate?: any;
    /**
     * 
     * @type {BookingPassengerDccStatusResponse}
     * @memberof BookingPassengerResponse
     */
    dccStatus?: any;
}
