/* tslint:disable */
/* eslint-disable */
/**
 * EU Digital COVID Certificate Booking Demo
 * The API provides exemplary booking endpoints
 *
 * OpenAPI spec version: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface BookingFlightInfoResponse
 */
export interface BookingFlightInfoResponse {
    /**
     * 
     * @type {string}
     * @memberof BookingFlightInfoResponse
     */
    from?: any;
    /**
     * 
     * @type {string}
     * @memberof BookingFlightInfoResponse
     */
    to?: any;
    /**
     * 
     * @type {Date}
     * @memberof BookingFlightInfoResponse
     */
    time?: any;
}
